name: vibette
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  bloc: ^9.0.0
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  flashy_tab_bar2: ^0.0.10
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_otp_text_field: ^1.4.0+2
  flutter_staggered_grid_view: ^0.7.0
  go_router: ^14.7.2
  google_fonts: ^6.2.1
  http: ^1.3.0
  like_button: ^2.0.5
  loading_animation_widget: ^1.3.0
  readmore: ^3.0.0
  shared_preferences: ^2.5.1
  shimmer: ^3.0.0
  sidebar_with_animation: ^0.0.3
  socket_io_client: ^3.0.2
dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
