// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZOFlLu36KRoiXqV3g0JrKJmN2kVKEZy0',
    appId: '1:769775379945:web:ba4b7d9c0cf79bfb2e5778',
    messagingSenderId: '769775379945',
    projectId: 'vibette-be3a3',
    authDomain: 'vibette-be3a3.firebaseapp.com',
    storageBucket: 'vibette-be3a3.firebasestorage.app',
    measurementId: 'G-N8EYCZCDKK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4I0xLznpm2ot-hXjKSl6Y-aQ3GIUyJZE',
    appId: '1:769775379945:android:6798f706ead9f87d2e5778',
    messagingSenderId: '769775379945',
    projectId: 'vibette-be3a3',
    storageBucket: 'vibette-be3a3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRkE2iKE2EsoAJ_Y-KG7fy967aREM-LDI',
    appId: '1:769775379945:ios:09b8096e16c0969c2e5778',
    messagingSenderId: '769775379945',
    projectId: 'vibette-be3a3',
    storageBucket: 'vibette-be3a3.firebasestorage.app',
    iosClientId: '769775379945-5m0aqrfdkoegnmjbamtnci0usv4h3451.apps.googleusercontent.com',
    iosBundleId: 'com.example.vibette',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRkE2iKE2EsoAJ_Y-KG7fy967aREM-LDI',
    appId: '1:769775379945:ios:09b8096e16c0969c2e5778',
    messagingSenderId: '769775379945',
    projectId: 'vibette-be3a3',
    storageBucket: 'vibette-be3a3.firebasestorage.app',
    iosClientId: '769775379945-5m0aqrfdkoegnmjbamtnci0usv4h3451.apps.googleusercontent.com',
    iosBundleId: 'com.example.vibette',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZOFlLu36KRoiXqV3g0JrKJmN2kVKEZy0',
    appId: '1:769775379945:web:c7bfd09342e65fe82e5778',
    messagingSenderId: '769775379945',
    projectId: 'vibette-be3a3',
    authDomain: 'vibette-be3a3.firebaseapp.com',
    storageBucket: 'vibette-be3a3.firebasestorage.app',
    measurementId: 'G-EV9QY7S9ND',
  );

}